spring.application.name=myApp

#DB settings
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_sys_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root


#Hibernate settings
spring.jpa.hibernate.ddl-auto=update