spring.application.name=gateway-service
eureka.instance.hostname=localhost
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
server.port=8080


# Gateway Config : enable location service
#spring.cloud.gateway.discovery.locator.enabled=true
# 2. Enable lowercase service names
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Routing Config : id, uri, predicate for each client in routes array
# Service : Account Service
# Route ID
spring.cloud.gateway.routes[0].id=account-service
# Target physical address of the service
spring.cloud.gateway.routes[0].uri=lb://account-service
# Matches any traffic starting with /location/
spring.cloud.gateway.routes[0].predicates[0]=Path=/account-service/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/account-service/(?<segment>.*), /${segment}

# Service : Payment Service
# Route ID
spring.cloud.gateway.routes[1].id=payment-service
# Target physical address of the service
spring.cloud.gateway.routes[1].uri=lb://payment-service
# Matches any traffic starting with /location/
spring.cloud.gateway.routes[1].predicates[0]=Path=/payment-service/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/payment-service/(?<segment>.*), /${segment}