spring.application.name=task-management-system


#DB settings
spring.datasource.url=jdbc:mysql://localhost:3306/task_sys_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root


#Hibernate settings
spring.jpa.hibernate.ddl-auto=update

#Security props
jwt.secret=secret